In [1]:
import numpy as np

In [16]:
A[2,2]
A[i,i]
i[2]

2

In [ ]:

A = np.array([[0,1,import nbimporter

import sys
sys.path.append('')
print(sys.path)

import os
print(os.getcwd())

import TCI_newmethod2],[2,3,4],[5,6,7]])
i = np.array([0,1,2])
print(A[i[:,None],i[None,:]])
print(A)

[[0 1 2]
 [2 3 4]
 [5 6 7]]
[[0 1 2]
 [2 3 4]
 [5 6 7]]
